resources:
  repositories:
    - repository: templates
      type: github
      name: FirelyTeam/azure-pipeline-templates
      endpoint: FirelyTeam
      
variables:
  buildConfiguration: 'Release'
  
stages:
- stage: build
  jobs:
  - template: build.yml@templates  # Template reference
    parameters:
      dotNetCoreVersion: '6.0.x'
      nuGetServiceConnections: GitHub_FirelyTeams_NuGetFeed
      nuGetSources: --source https://nuget.pkg.github.com/FirelyTeam/index.json
      pool:
         vmImage: ubuntu-latest
      restoreDependencies: true
      useVersionSuffix: false 
