# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  repositories:
    - repository: templates
      type: github
      name: FirelyTeam/azure-pipeline-templates
      endpoint: FirelyTeam
    
stages:
- stage: build
  jobs:
  - template: build.yml@templates  # Template reference
    parameters:
      dotNetCoreVersion: '6.0.x'
      nuGetServiceConnections: GitHub_FirelyTeams_NuGetFeed
      nuGetSources: --source https://nuget.pkg.github.com/FirelyTeam/index.json
      packageArtifacts: true
      pool:
         vmImage: ubuntu-latest
      restoreDependencies: true
      useVersionSuffix: false 
